variables:
  system.debug: true
  ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
    branchName: ''
  ${{ if ne( variables['Build.SourceBranchName'], 'main') }}:
    branchName: -${{ variables['Build.SourceBranchName'] }}

name: 'ChonkyBot-$(Rev:r)$(branchName)'

trigger:
  paths:
    include:
      - 'ChonkyBot/*'

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'ChonkyBot/*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'StockDataLibraryTests/*.csproj'
  env:
    ConnectionString: $(ConnectionString)

- task: Docker@2
  inputs:
    command: 'buildAndPush'
    Dockerfile: 'ChonkyBot/Dockerfile'
    containerRegistry: 'registry'
    buildContext: $(Build.Repository.LocalPath)
    repository: 'chonkybot$(branchName)'
    tags: |
      $(Build.BuildId)
      latest
