variables:
  system.debug: true
  ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
    branchName: ''
  ${{ if ne( variables['Build.SourceBranchName'], 'main') }}:
    branchName: -${{ variables['Build.SourceBranchName'] }}

name: 'TDAStreamer-$(Rev:r)$(branchName)'
# Starter pipeline
pool:
  vmImage: ubuntu-latest

trigger:
  paths:
    include:
      - 'TDAStreamer/*'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'TDAStreamer/*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*.csproj'
  env:
    ConnectionString: $(ConnectionString)

- task: Docker@2
  inputs:
    command: 'buildAndPush'
    Dockerfile: 'TDAStreamer/Dockerfile'
    containerRegistry: 'registry'
    buildContext: $(Build.Repository.LocalPath)
    repository: 'TDAStreamer$(branchName)'
    tags: |
      $(Build.BuildId)
      latest