// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StockDataLibrary.Db;

namespace StockDataLibrary.Migrations
{
    [DbContext(typeof(DataDbContext))]
    [Migration("20210419233115_AddTradierSnapshotFields")]
    partial class AddTradierSnapshotFields
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("StockDataLibrary.Models.OratsOptionChain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<float>("LocalCallOptionDelta")
                        .HasColumnType("real");

                    b.Property<float>("LocalPutOptionDelta")
                        .HasColumnType("real");

                    b.Property<long>("QuoteDate")
                        .HasColumnType("bigint");

                    b.Property<string>("RawData")
                        .HasColumnType("text");

                    b.Property<int>("StockId")
                        .HasColumnType("integer");

                    b.Property<float>("TotalCallOptionDelta")
                        .HasColumnType("real");

                    b.Property<float>("TotalPutOptionDelta")
                        .HasColumnType("real");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StockId", "QuoteDate")
                        .IsUnique();

                    b.ToTable("OratsOptionChains");
                });

            modelBuilder.Entity("StockDataLibrary.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("StockDataLibrary.Models.TradierSnapshot", b =>
                {
                    b.Property<long>("Time")
                        .HasColumnType("bigint");

                    b.Property<int>("SymbolId")
                        .HasColumnType("integer");

                    b.Property<float>("Close")
                        .HasColumnType("real");

                    b.Property<long>("CloseTime")
                        .HasColumnType("bigint");

                    b.Property<long>("CumulativeVolume")
                        .HasColumnType("bigint");

                    b.Property<float>("High")
                        .HasColumnType("real");

                    b.Property<long>("LocalTimesaleVolume")
                        .HasColumnType("bigint");

                    b.Property<long>("LocalVolume")
                        .HasColumnType("bigint");

                    b.Property<float>("Low")
                        .HasColumnType("real");

                    b.Property<float>("Open")
                        .HasColumnType("real");

                    b.Property<long>("OpenTime")
                        .HasColumnType("bigint");

                    b.Property<long>("TimesaleCount")
                        .HasColumnType("bigint");

                    b.Property<long>("TradeCount")
                        .HasColumnType("bigint");

                    b.HasKey("Time", "SymbolId");

                    b.ToTable("TradierSnapshots");
                });

            modelBuilder.Entity("StockDataLibrary.Models.OratsOptionChain", b =>
                {
                    b.HasOne("StockDataLibrary.Models.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });
#pragma warning restore 612, 618
        }
    }
}
